module.exports = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_NOT_VERIFIED: 'AUTH_ACCOUNT_NOT_VERIFIED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Delivery Order Error Codes
  DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  DELIVERY_ALREADY_VALIDATED: 'DELIVERY_ALREADY_VALIDATED',
  DELIVERY_ALREADY_CANCELED: 'DELIVERY_ALREADY_CANCELED',

  // Stock Transfer Error Codes
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  TRANSFER_INVALID_STATUS: 'TRANSFER_INVALID_STATUS',
  TRANSFER_SOURCE_DESTINATION_SAME: 'TRANSFER_SOURCE_DESTINATION_SAME',
  TRANSFER_EMPTY_ITEMS: 'TRANSFER_EMPTY_ITEMS',
  TRANSFER_DUPLICATE_PRODUCT: 'TRANSFER_DUPLICATE_PRODUCT',
  TRANSFER_INSUFFICIENT_STOCK: 'TRANSFER_INSUFFICIENT_STOCK',
  TRANSFER_ALREADY_COMPLETED: 'TRANSFER_ALREADY_COMPLETED',
  TRANSFER_CANNOT_CANCEL: 'TRANSFER_CANNOT_CANCEL',
  TRANSFER_INVALID_LOCATION: 'TRANSFER_INVALID_LOCATION',
  TRANSFER_INVALID_WAREHOUSE: 'TRANSFER_INVALID_WAREHOUSE',

  // Notification Error Codes
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_ACCESS_DENIED: 'NOTIFICATION_ACCESS_DENIED',
  INVALID_NOTIFICATION_TYPE: 'INVALID_NOTIFICATION_TYPE',
  INVALID_NOTIFICATION_SEVERITY: 'INVALID_NOTIFICATION_SEVERITY',
  INVALID_NOTIFICATION_STATUS: 'INVALID_NOTIFICATION_STATUS',

  // Audit Log Error Codes
  AUDIT_LOG_NOT_FOUND: 'AUDIT_LOG_NOT_FOUND',
  AUDIT_ACCESS_DENIED: 'AUDIT_ACCESS_DENIED',
  INVALID_AUDIT_ACTION: 'INVALID_AUDIT_ACTION',
  INVALID_AUDIT_MODULE: 'INVALID_AUDIT_MODULE'
};
